---
- name: install docker
  import_tasks: docker.yml

- name: git clone
  import_tasks: git.yml

- name: application deploy
  import_tasks: app.yml

- name: proxy pass via nginx
  import_tasks: nginx.yml
